CREATE TABLE [dbo].[EmplPlan_backup]
(
[PlanID] [int] NOT NULL IDENTITY(1, 1),
[PlanYear] [int] NOT NULL,
[PlanTypeID] [int] NOT NULL,
[PlanStartDt] [datetime] NULL,
[PlanSchedEndDt] [datetime] NULL,
[PlanEvalSign] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanEmplSign] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanEvalSignDt] [datetime] NULL,
[PlanEmplSignDt] [datetime] NULL,
[PlanActive] [bit] NOT NULL,
[PlanEditLock] [bit] NOT NULL,
[EmplJobID] [int] NOT NULL,
[CreatedByID] [nchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreatedByDt] [datetime] NOT NULL,
[LastUpdatedByID] [nchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LastUpdatedDt] [datetime] NOT NULL,
[GoalStatusID] [int] NULL,
[GoalStatusDt] [datetime] NULL,
[IsSigned] [bit] NOT NULL,
[Signature] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateSigned] [datetime] NULL,
[IsSignedAsmt] [bit] NOT NULL,
[SignatureAsmt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateSignedAsmt] [datetime] NULL,
[Duration] [int] NOT NULL,
[SubEvalID] [nchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SelfAsmtStrength] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelfAsmtWeakness] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrescriptEvalID] [int] NULL,
[HasPrescript] [bit] NOT NULL,
[ActnStepStatusID] [int] NULL,
[ActnStepDt] [datetime] NULL,
[IsSignedActnStep] [bit] NOT NULL,
[SignatureActnStep] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateSignedActnStep] [datetime] NULL,
[NeedToEnd] [bit] NOT NULL,
[PlanActEndDt] [datetime] NULL,
[PlanEndReasonID] [int] NULL,
[PlanStartEvalDate] [datetime] NULL,
[RubricID] [int] NULL,
[IsMultiYearPlan] [bit] NULL,
[MultiYearGoalStatusID] [int] NULL,
[MultiYearGoalStatusDt] [datetime] NULL,
[MultiYearActnStepStatusID] [int] NULL,
[MultiYearActnStepDt] [datetime] NULL,
[PrevPlanPrescptEvalID] [int] NULL,
[FormativeStartDt] [date] NULL,
[FormativeEndDt] [date] NULL,
[AnticipatedEvalWeek] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanManagerID] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GoalFirstSubmitDt] [datetime] NULL,
[IsInvalid] [int] NOT NULL,
[InvalidNote] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
