IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ADMINDOM\bpssvc')
CREATE LOGIN [ADMINDOM\bpssvc] FROM WINDOWS
GO
CREATE USER [bpssvc] FOR LOGIN [ADMINDOM\bpssvc] WITH DEFAULT_SCHEMA=[bpssvc]
GO
